export type PluginStatus = 'enabled' | 'disabled' | 'installing' | 'error' | 'not_installed'
export type PluginCategory = 'threat-protection' | 'monitoring' | 'scanning' | 'network' | 'compliance'

export interface PluginConfigField {
  key: string; label: string; type: 'text'|'number'|'boolean'|'select'
  value: string|number|boolean; options?: string[]; description: string
}
export interface Plugin {
  id: string; name: string; shortName: string; version: string
  description: string; longDescription: string
  category: PluginCategory; status: PluginStatus
  author: string; website: string; license: string; size: string
  tags: string[]
  config: PluginConfigField[]
  features: string[]
  dependencies: string[]
  installCommand: string
}

export const PLUGINS: Plugin[] = [
  {
    id: 'fail2ban',
    name: 'Fail2Ban',
    shortName: 'F2B',
    version: '1.0.2',
    description: 'Brute-force attack prevention by monitoring logs and banning offending IPs via iptables/nftables.',
    longDescription: 'Fail2Ban scans log files and bans IPs that show malicious signs — too many password failures, seeking exploits, etc. It updates firewall rules to reject the IP for a configurable amount of time. Out of the box Fail2Ban comes with filters for various services (apache, courier, ssh, etc).',
    category: 'threat-protection',
    status: 'enabled',
    author: 'Fail2Ban Project',
    website: 'https://www.fail2ban.org',
    license: 'GPL-2.0',
    size: '1.2 MB',
    tags: ['brute-force', 'iptables', 'ssh', 'nginx', 'ban'],
    config: [
      { key:'bantime',      label:'Ban Time (seconds)',   type:'number',  value:7200,   description:'Duration for which an IP is banned after triggering a jail' },
      { key:'findtime',     label:'Find Time (seconds)',  type:'number',  value:600,    description:'Time window in which maxretry failures triggers a ban' },
      { key:'maxretry',     label:'Max Retry',            type:'number',  value:5,      description:'Maximum number of failures before banning an IP' },
      { key:'ignoreself',   label:'Ignore Self',          type:'boolean', value:true,   description:'Do not ban the server\'s own IP addresses' },
      { key:'backend',      label:'Backend',              type:'select',  value:'auto', options:['auto','pyinotify','gamin','polling','systemd'], description:'Backend used to detect modifications in log files' },
      { key:'usedns',       label:'Use DNS',              type:'select',  value:'warn', options:['yes','no','warn','raw'], description:'Whether to use DNS lookups for ban decisions' },
    ],
    features: ['Auto-ban IPs on repeated failures','Multiple jail support (SSH, Nginx, Postfix)','Whitelist management','iptables & nftables integration','Email/webhook notifications on bans','Recidive jail for repeat offenders'],
    dependencies: ['iptables or nftables', 'python3'],
    installCommand: 'apt-get install -y fail2ban && systemctl enable --now fail2ban',
  },
  {
    id: 'crowdsec',
    name: 'CrowdSec',
    shortName: 'CS',
    version: '1.6.1',
    description: 'Collaborative threat intelligence platform that leverages the crowd to block malicious IPs globally.',
    longDescription: 'CrowdSec is a free, open source, and collaborative IPS. It analyzes behaviors, responds to attacks & shares signals across the community. When your CrowdSec installation blocks an attack, the IP is reported to the CrowdSec central API, which then distributes it to all other CrowdSec users.',
    category: 'threat-protection',
    status: 'enabled',
    author: 'CrowdSec',
    website: 'https://crowdsec.net',
    license: 'MIT',
    size: '42 MB',
    tags: ['threat-intelligence', 'collaborative', 'ip-reputation', 'bouncer'],
    config: [
      { key:'api_url',         label:'Central API URL',       type:'text',    value:'https://api.crowdsec.net/', description:'URL of the CrowdSec Central API' },
      { key:'log_level',       label:'Log Level',             type:'select',  value:'info', options:['debug','info','warn','error'], description:'Log verbosity level' },
      { key:'prometheus_port', label:'Prometheus Port',       type:'number',  value:6060, description:'Port to expose Prometheus metrics on' },
      { key:'capi_whitelists', label:'Community Blocklist',   type:'boolean', value:true, description:'Pull and apply community-sourced blocklists' },
      { key:'online_client',   label:'Share Decisions',       type:'boolean', value:true, description:'Contribute your decisions to the CrowdSec community' },
    ],
    features: ['Real-time threat detection', 'Community-sourced blocklists','Multiple bouncer support','CAPI integration for global threat intelligence','Custom scenarios','Prometheus metrics'],
    dependencies: ['iptables bouncer or nginx bouncer'],
    installCommand: 'curl -s https://packagecloud.io/install/repositories/crowdsec/crowdsec/script.deb.sh | bash && apt install -y crowdsec',
  },
  {
    id: 'wazuh',
    name: 'Wazuh',
    shortName: 'WZH',
    version: '4.7.0',
    description: 'Open-source XDR & SIEM platform — threat detection, compliance, file integrity monitoring.',
    longDescription: 'Wazuh is a free and open-source security platform that unifies XDR and SIEM protection for endpoints and cloud workloads. It provides threat prevention, detection, and response capabilities through security telemetry analysis, compliance management, and file integrity monitoring.',
    category: 'monitoring',
    status: 'enabled',
    author: 'Wazuh',
    website: 'https://wazuh.com',
    license: 'GPL-2.0',
    size: '312 MB',
    tags: ['xdr', 'siem', 'fim', 'compliance', 'threat-detection'],
    config: [
      { key:'manager_host',   label:'Manager Host',         type:'text',    value:'wazuh-manager.local', description:'Wazuh manager hostname or IP' },
      { key:'manager_port',   label:'Manager Port',         type:'number',  value:1514, description:'Port for agent-manager communication' },
      { key:'fim_enabled',    label:'File Integrity Mon.',  type:'boolean', value:true, description:'Enable file integrity monitoring' },
      { key:'rootcheck',      label:'Rootkit Detection',    type:'boolean', value:true, description:'Enable rootkit and malware detection' },
      { key:'log_level',      label:'Log Level',            type:'select',  value:'info', options:['debug','info','warning','error'], description:'Logging verbosity' },
    ],
    features: ['File integrity monitoring (FIM)','Threat intelligence & CVE detection','MITRE ATT&CK mapping','Compliance (PCI-DSS, HIPAA, GDPR)','Log analysis & correlation','Active response automation'],
    dependencies: ['curl', 'apt-transport-https'],
    installCommand: 'curl -sO https://packages.wazuh.com/4.7/wazuh-install.sh && bash ./wazuh-install.sh -a',
  },
  {
    id: 'suricata',
    name: 'Suricata',
    shortName: 'SUR',
    version: '7.0.3',
    description: 'High-performance network IDS, IPS, and network security monitoring engine.',
    longDescription: 'Suricata is a free and open-source network threat detection engine. It is capable of real time intrusion detection (IDS), inline intrusion prevention (IPS), network security monitoring (NSM) and offline pcap processing.',
    category: 'network',
    status: 'enabled',
    author: 'OISF',
    website: 'https://suricata.io',
    license: 'GPL-2.0',
    size: '28 MB',
    tags: ['ids', 'ips', 'network', 'packet-inspection', 'nids'],
    config: [
      { key:'interface',      label:'Network Interface',   type:'text',    value:'eth0',   description:'Network interface to monitor' },
      { key:'mode',           label:'Mode',                type:'select',  value:'ids',    options:['ids','ips','monitor'], description:'Operating mode: IDS (alert), IPS (block), or monitoring only' },
      { key:'rule_reload',    label:'Auto Rule Reload',    type:'boolean', value:true,     description:'Automatically reload rules when they change' },
      { key:'af_packet',      label:'AF-PACKET Mode',      type:'boolean', value:true,     description:'Use AF-PACKET for high-performance capture' },
      { key:'log_fast',       label:'Fast Log',            type:'boolean', value:true,     description:'Enable fast.log for quick alert output' },
    ],
    features: ['Real-time IDS/IPS','Deep packet inspection','Protocol identification','File extraction','TLS/SSL inspection','Lua scripting for custom rules','EVE JSON logging'],
    dependencies: ['libpcap', 'libyaml'],
    installCommand: 'apt-get install -y suricata && systemctl enable --now suricata',
  },
  {
    id: 'clamav',
    name: 'ClamAV',
    shortName: 'CLA',
    version: '1.3.0',
    description: 'Open-source antivirus engine for detecting trojans, viruses, malware, and other threats.',
    longDescription: 'ClamAV is an open-source (GPL) anti-virus toolkit designed especially for e-mail scanning on mail gateways. It provides a number of utilities including a flexible and scalable multi-threaded daemon, a command line scanner, and advanced tool for automatic database updates.',
    category: 'scanning',
    status: 'enabled',
    author: 'Cisco Talos',
    website: 'https://www.clamav.net',
    license: 'GPL-2.0',
    size: '8.4 MB',
    tags: ['antivirus', 'malware', 'scanner', 'quarantine'],
    config: [
      { key:'scan_path',       label:'Scan Path',            type:'text',    value:'/',        description:'Root path to scan (use / for full system)' },
      { key:'exclude_paths',   label:'Exclude Paths',        type:'text',    value:'/proc /sys /dev', description:'Space-separated paths to exclude from scanning' },
      { key:'schedule',        label:'Scan Schedule (cron)', type:'text',    value:'0 2 * * *',description:'Cron expression for scheduled scans' },
      { key:'quarantine_dir',  label:'Quarantine Dir',       type:'text',    value:'/var/quarantine', description:'Directory to move infected files to' },
      { key:'freshclam_auto',  label:'Auto Update Defs',     type:'boolean', value:true,       description:'Automatically update virus definitions via freshclam' },
    ],
    features: ['Real-time file scanning','Scheduled full-system scans','Automatic virus definition updates','Quarantine management','Email attachment scanning','Archive scanning (zip, tar, gz)'],
    dependencies: ['freshclam'],
    installCommand: 'apt-get install -y clamav clamav-daemon && freshclam && systemctl enable --now clamav-daemon',
  },
  {
    id: 'trivy',
    name: 'Trivy',
    shortName: 'TRV',
    version: '0.50.1',
    description: 'Comprehensive container & infrastructure vulnerability scanner by Aqua Security.',
    longDescription: 'Trivy is a comprehensive and versatile security scanner. Trivy has scanners that look for security issues in container images, file systems, Git repositories, virtual machine images, Kubernetes, and AWS. It detects vulnerabilities, misconfigurations, secrets, SBOM, and license issues.',
    category: 'scanning',
    status: 'enabled',
    author: 'Aqua Security',
    website: 'https://trivy.dev',
    license: 'Apache-2.0',
    size: '94 MB',
    tags: ['container', 'vulnerability', 'sbom', 'cve', 'docker'],
    config: [
      { key:'scan_target',     label:'Scan Target',          type:'text',    value:'.',         description:'Target to scan (image name, directory, or git repo)' },
      { key:'severity',        label:'Min Severity',         type:'select',  value:'MEDIUM',    options:['UNKNOWN','LOW','MEDIUM','HIGH','CRITICAL'], description:'Minimum severity level to report' },
      { key:'ignore_unfixed',  label:'Ignore Unfixed',       type:'boolean', value:false,       description:'Ignore vulnerabilities without a fix available' },
      { key:'auto_scan',       label:'Auto Scan on Pull',    type:'boolean', value:true,        description:'Automatically scan images when pulled' },
      { key:'output_format',   label:'Output Format',        type:'select',  value:'table',     options:['table','json','sarif','cyclonedx'], description:'Output format for scan results' },
    ],
    features: ['Container image scanning','OS & language package vulnerability detection','SBOM generation (CycloneDX, SPDX)','Secret detection','Misconfiguration scanning','Git repository scanning','CI/CD integration'],
    dependencies: [],
    installCommand: 'curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.50.1',
  },
  {
    id: 'docker-security',
    name: 'Docker Security',
    shortName: 'DSC',
    version: '2.1.0',
    description: 'Container security hardening — detect privileged containers, exposed sockets, root users, and misconfigurations.',
    longDescription: 'Docker Security plugin continuously monitors your Docker containers for security misconfigurations including privileged containers, containers running as root, exposed Docker sockets, dangerous capabilities, and image vulnerabilities. Provides guided remediation for each finding.',
    category: 'scanning',
    status: 'disabled',
    author: 'Orbit VPS',
    website: '#',
    license: 'MIT',
    size: '3.1 MB',
    tags: ['docker', 'container', 'hardening', 'cis-benchmark'],
    config: [
      { key:'socket_path',     label:'Docker Socket',        type:'text',    value:'/var/run/docker.sock', description:'Path to Docker socket' },
      { key:'scan_interval',   label:'Scan Interval (min)',  type:'number',  value:15, description:'How often to scan containers (minutes)' },
      { key:'alert_privileged',label:'Alert on Privileged',  type:'boolean', value:true, description:'Alert when privileged containers are detected' },
      { key:'alert_root',      label:'Alert on Root User',   type:'boolean', value:true, description:'Alert when containers run as root' },
    ],
    features: ['Privileged container detection','Root user detection','Dangerous capabilities audit','CIS Docker Benchmark','Image vulnerability linking','Auto-remediation suggestions','Real-time event monitoring'],
    dependencies: ['docker'],
    installCommand: 'orbit plugin install docker-security',
  },
  {
    id: 'lynis',
    name: 'Lynis',
    shortName: 'LYN',
    version: '3.0.9',
    description: 'Security auditing and hardening tool for Unix/Linux systems — compliance and configuration assessment.',
    longDescription: 'Lynis is an open source security auditing tool. Used by system administrators, security professionals, and auditors to evaluate the security defenses of their Linux and Unix-based systems. It performs an in-depth security scan on the host to detect security issues and provide suggestions for hardening.',
    category: 'compliance',
    status: 'disabled',
    author: 'CISOfy',
    website: 'https://cisofy.com/lynis',
    license: 'GPL-3.0',
    size: '1.8 MB',
    tags: ['audit', 'hardening', 'compliance', 'cis', 'benchmark'],
    config: [
      { key:'cronjob',    label:'Schedule (cron)',   type:'text',    value:'0 3 * * 0', description:'Weekly cron expression for automated scans' },
      { key:'profile',    label:'Audit Profile',     type:'select',  value:'default', options:['default','developer','hipaa','pci-dss'], description:'Audit profile to use' },
      { key:'report_dir', label:'Report Directory',  type:'text',    value:'/var/log/lynis', description:'Directory to store reports' },
      { key:'verbose',    label:'Verbose Output',    type:'boolean', value:false, description:'Enable verbose logging' },
    ],
    features: ['Full system security audit','Software patch management check','Malware scanner detection','Kernel security settings','File permissions audit','Authentication checks','Network configuration review'],
    dependencies: [],
    installCommand: 'apt-get install -y lynis',
  },
  {
    id: 'rkhunter',
    name: 'RKHunter',
    shortName: 'RKH',
    version: '1.4.6',
    description: 'Rootkit, backdoor, and local exploit scanner for Linux/Unix systems.',
    longDescription: 'Rootkit Hunter (RKHunter) is a Unix-based tool that scans for rootkits, backdoors, and possible local exploits. It does this by comparing SHA-1 hashes of important files with known good ones in online databases, searching for default directories (of rootkits), wrong permissions, hidden files, suspicious strings in kernel modules, and special tests for Linux.',
    category: 'scanning',
    status: 'not_installed',
    author: 'RKHunter Project',
    website: 'http://rkhunter.sourceforge.net',
    license: 'GPL-2.0',
    size: '820 KB',
    tags: ['rootkit', 'backdoor', 'forensics', 'integrity'],
    config: [
      { key:'cron_daily',  label:'Daily Scan',           type:'boolean', value:true,           description:'Enable daily scheduled scans' },
      { key:'mail_on_warn',label:'Email on Warning',     type:'boolean', value:true,           description:'Send email alerts when warnings are found' },
      { key:'update_auto', label:'Auto Update Defs',     type:'boolean', value:true,           description:'Automatically update rootkit database' },
    ],
    features: ['Rootkit database scanning','Backdoor detection','File hash verification','Hidden file detection','Network port analysis','Suspicious string detection in kernel modules'],
    dependencies: ['wget', 'unhide'],
    installCommand: 'apt-get install -y rkhunter && rkhunter --update && rkhunter --propupd',
  },
  {
    id: 'github-actions',
    name: 'Git Actions',
    shortName: 'GHA',
    version: '1.0.0',
    description: 'CI/CD pipeline runner — trigger builds and deployments from GitHub, GitLab, Gitea, and Bitbucket webhooks.',
    longDescription: 'Git Actions lets you define workflows that automatically run build, test, and deploy commands when code is pushed to your repository. Connect any Git provider via webhooks, configure per-branch pipelines, view live logs, and get notified on success or failure.',
    category: 'monitoring',
    status: 'not_installed',
    author: 'Orbit VPS',
    website: 'https://github.com',
    license: 'MIT',
    size: '2.4 MB',
    tags: ['ci-cd', 'github', 'gitlab', 'gitea', 'webhook', 'deploy', 'automation'],
    config: [],
    features: ['Webhook triggers from GitHub, GitLab, Gitea, Bitbucket','Multi-branch pipeline support','Pre-build, build, deploy, and post-deploy commands','Live run log streaming','Run history with retry and cancel','HMAC webhook signature verification','Notification on success/failure'],
    dependencies: ['bash', 'git'],
    installCommand: 'systemctl enable --now orbit-git-actions',
  },
]

export function getPlugin(id: string): Plugin | undefined {
  return PLUGINS.find(p => p.id === id)
}
